name: .NET Build
description: Sets up Nushell, .NET SDK, collects build info from knope.toml, and optionally builds

inputs:
  setup-dotnet:
    description: Whether to setup .NET SDK
    required: false
    default: "true"
  build:
    description: Whether to build and create Thunderstore package
    required: false
    default: "false"

outputs:
  version:
    description: Version from csproj
    value: ${{ steps.info.outputs.version }}
  csproj:
    description: Path to csproj file
    value: ${{ steps.info.outputs.csproj }}
  sha_short:
    description: Short commit SHA
    value: ${{ steps.info.outputs.sha_short }}

runs:
  using: composite
  steps:
    - uses: hustcer/setup-nu@920172d92eb04671776f3ba69d605d3b09351c30 # v3
      with:
        version: "0.110.0"

    - name: Collect build info
      id: info
      shell: nu {0}
      run: |
        let sha_short = git rev-parse --short HEAD | str trim
        let csproj = open knope.toml | get package.versioned_files.0.path
        let version = open $csproj --raw | from xml | get content | where tag == "PropertyGroup" | first | get content | where tag == "Version" | first | get content | first | get content
        $"sha_short=($sha_short)\n" | save -a --raw $env.GITHUB_OUTPUT
        $"csproj=($csproj)\n" | save -a --raw $env.GITHUB_OUTPUT
        $"version=($version)\n" | save -a --raw $env.GITHUB_OUTPUT

    - uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
      if: inputs.setup-dotnet == 'true'
      with:
        global-json-file: global.json

    - name: Build
      if: inputs.build == 'true'
      shell: bash
      run: dotnet build -c Release

    - name: Create Thunderstore Package
      if: inputs.build == 'true'
      shell: nu {0}
      run: |
        let csproj = open knope.toml | get package.versioned_files.0.path
        let version = open $csproj --raw | from xml | get content | where tag == "PropertyGroup" | first | get content | where tag == "Version" | first | get content | first | get content
        dotnet tool restore
        dotnet tcli build --package-version $version
